In [1]:
import pandas as pd

In [2]:
dm = pd.read_csv("~/Downloads/DM-History-20171101.csv")
price = pd.read_csv("~/Downloads/Price-History-20171101.csv")

In [3]:
dm.head()

,Date,3137G0AM1,3137G0AY5,3137G0BK4,3137G0BW8,3137G0CH0,3137G0CU1,3137G0DF3,3137G0DW6,3137G0EJ4,...,30711XEP5,30711XGP3,30711XJX3,30711XLT9,2016 Index,2016 High Index,2016 Low Index,2015 Index,2014/2015 High Index,2014/2015 Low Index
0,4/6/2016,453.966,438.093,428.742,437.534,462.945,448.747,455.669,400.278,437.333,...,NaN,NaN,NaN,NaN,,,,471.578,471.178,457.467
1,4/7/2016,452.983,442.780,428.742,432.602,461.576,445.854,457.113,399.166,435.861,...,NaN,NaN,NaN,NaN,,,,470.609,470.402,456.708
2,4/8/2016,452.000,436.736,426.366,430.136,459.749,442.639,453.648,395.277,433.407,...,NaN,NaN,NaN,NaN,,,,467.993,467.951,454.037
3,4/11/2016,444.525,435.593,425.124,430.102,457.934,442.711,450.514,398.166,434.615,...,NaN,NaN,NaN,NaN,,,,464.325,465.465,450.383
4,4/12/2016,444.525,435.593,424.285,429.116,456.564,441.746,449.359,396.778,433.143,...,NaN,NaN,NaN,NaN,,,,463.855,464.851,449.897

In [4]:
price.head()

,Date,3137G0AM1,3137G0AY5,3137G0BK4,3137G0BW8,3137G0CH0,3137G0CU1,3137G0DF3,3137G0DW6,3137G0EJ4,...,30711XEP5,30711XGP3,30711XJX3,30711XLT9,2016 Index,2016 High Index,2016 Low Index,2015 Index,2014/2015 High Index,2014/2015 Low Index
0,4/6/2016,100.000,94.500,98.398,98.250,93.891,99.984,101.109,100.266,96.438,...,NaN,NaN,NaN,NaN,,,,99.187,97.888,97.654
1,4/7/2016,100.063,94.203,98.398,98.563,93.984,100.125,101.031,100.328,96.531,...,NaN,NaN,NaN,NaN,,,,99.243,97.937,97.694
2,4/8/2016,100.125,94.586,98.531,98.719,94.109,100.281,101.219,100.547,96.688,...,NaN,NaN,NaN,NaN,,,,99.393,98.071,97.844
3,4/11/2016,100.473,94.948,98.599,98.719,94.310,100.437,101.419,100.656,96.607,...,NaN,NaN,NaN,NaN,,,,99.477,98.103,97.988
4,4/12/2016,100.473,94.948,98.646,98.782,94.404,100.484,101.482,100.734,96.701,...,NaN,NaN,NaN,NaN,,,,99.491,98.125,98.001

In [5]:
dm.dropna().shape

(89, 62)

In [6]:
price.dropna().shape

(89, 62)

In [7]:
dm = dm.dropna()
price = price.dropna()

In [8]:
dm.reset_index(drop=True, inplace=True)
price.reset_index(drop=True, inplace=True)

In [9]:
dm

,Date,3137G0AM1,3137G0AY5,3137G0BK4,3137G0BW8,3137G0CH0,3137G0CU1,3137G0DF3,3137G0DW6,3137G0EJ4,...,30711XEP5,30711XGP3,30711XJX3,30711XLT9,2016 Index,2016 High Index,2016 Low Index,2015 Index,2014/2015 High Index,2014/2015 Low Index
0,6/30/2017,161.000,160.750,177.000,204.997,213.638,198.996,219.495,177.749,184.994,...,251.959,253.184,252.373,263.138,243.056,248.309,239.480,210.743,200.131,178.523
1,7/3/2017,160.232,160.186,176.105,204.344,213.242,197.939,218.546,176.629,184.283,...,251.959,253.184,252.373,263.138,242.324,247.583,238.743,209.822,199.225,177.671
2,7/4/2017,160.232,160.186,176.105,204.344,213.242,197.939,218.546,176.629,184.283,...,251.959,253.184,252.373,263.138,242.324,247.583,238.743,209.822,199.225,177.671
3,7/5/2017,161.656,161.498,177.606,205.709,214.438,199.529,220.074,177.259,185.679,...,249.861,254.358,253.444,264.166,243.348,248.208,240.038,209.370,200.732,184.042
4,7/6/2017,162.713,162.541,178.671,206.760,215.439,200.603,221.141,179.845,189.291,...,250.402,250.153,251.455,263.179,241.697,246.853,238.187,209.713,201.550,177.633
5,7/7/2017,162.773,162.584,178.738,192.855,215.463,200.681,206.235,181.094,189.343,...,250.425,244.703,251.977,261.118,241.055,246.377,237.432,209.855,199.265,176.992
6,7/10/2017,162.233,162.189,178.105,192.358,215.176,199.931,205.515,180.307,188.847,...,250.216,244.463,251.887,261.069,240.803,246.389,236.999,209.197,198.623,176.218
7,7/11/2017,154.405,162.189,178.105,192.358,196.754,199.931,205.515,180.307,188.847,...,245.243,240.993,247.880,254.891,238.463,243.545,235.002,207.572,197.355,174.187
8,7/12/2017,147.369,151.661,169.855,189.114,146.795,189.830,202.379,177.201,185.596,...,216.440,229.436,224.437,228.465,220.234,226.956,215.657,200.791,189.276,167.509
9,7/13/2017,147.369,151.661,169.855,189.114,145.997,189.830,202.379,174.750,185.596,...,213.000,219.493,213.500,219.999,219.236,225.109,215.237,200.753,187.423,167.178
10,7/14/2017,142.129,143.250,167.484,189.114,145.997,187.484,202.379,173.750,183.497,...,208.000,212.498,206.749,218.500,218.067,223.733,214.210,198.670,185.648,163.925
11,7/17/2017,140.222,144.075,165.460,187.339,144.020,188.260,197.206,172.504,181.709,...,205.070,207.547,204.970,217.283,212.210,219.021,207.573,196.837,182.847,162.980
12,7/18/2017,140.019,144.616,172.198,187.884,144.558,188.828,197.774,174.758,182.259,...,205.599,208.078,205.988,217.797,210.286,216.837,205.826,197.536,183.406,163.701
13,7/19/2017,145.869,159.742,178.089,194.129,150.382,194.888,204.423,177.999,190.161,...,213.294,215.786,220.399,228.270,218.703,224.094,215.032,204.753,190.404,170.733
14,7/20/2017,142.241,152.339,178.202,194.259,151.498,193.553,204.589,178.171,190.214,...,212.825,219.981,219.445,225.901,218.650,223.676,215.228,204.508,190.388,169.976
15,7/21/2017,142.241,152.339,178.202,194.259,151.498,193.553,204.589,178.171,190.214,...,212.825,219.981,219.445,225.901,218.650,223.676,215.228,204.508,190.388,169.976
16,7/24/2017,141.773,151.745,176.467,192.275,151.525,191.586,207.050,176.306,188.455,...,212.099,220.474,220.022,225.871,218.075,222.899,214.790,203.226,188.677,169.181
17,7/25/2017,141.773,151.745,176.467,192.275,151.525,191.586,207.050,176.229,188.956,...,212.099,220.474,218.538,225.871,217.734,221.171,215.394,203.163,188.686,168.391
18,7/26/2017,142.012,152.085,177.413,193.151,151.675,191.945,207.274,174.017,189.177,...,218.421,218.729,219.171,222.507,218.087,221.513,215.755,203.967,189.277,169.088
19,7/27/2017,147.501,152.085,177.413,193.248,151.750,191.945,207.386,174.017,189.177,...,218.950,218.642,219.593,222.235,218.155,221.607,215.805,203.902,189.390,169.328
20,7/28/2017,147.493,152.085,177.413,193.248,151.750,191.945,207.386,174.017,189.177,...,218.950,218.642,218.496,222.525,218.155,221.607,215.805,203.926,189.374,169.422
21,7/31/2017,146.738,151.529,176.535,192.579,151.242,190.900,206.408,174.883,188.487,...,218.589,218.258,218.068,222.354,216.720,220.846,213.911,203.505,189.196,168.672
22,8/1/2017,147.091,152.258,178.084,194.085,152.212,191.904,207.375,175.383,189.085,...,219.834,215.300,218.891,222.380,217.271,221.373,214.479,204.121,189.918,169.291
23,8/2/2017,146.756,151.379,178.280,194.241,152.328,192.143,207.608,173.626,187.286,...,219.913,215.386,218.936,221.917,217.309,221.622,214.373,204.263,190.221,169.076
24,8/3/2017,150.344,150.631,179.798,193.314,152.405,193.724,211.740,175.253,175.649,...,221.422,216.668,220.973,224.728,218.859,223.163,215.929,203.695,189.617,169.869
25,8/4/2017,151.891,152.164,181.347,194.838,153.926,195.278,201.996,176.827,175.948,...,225.498,218.191,226.000,225.250,220.963,225.901,217.601,205.054,189.949,171.569
26,8/7/2017,153.278,153.708,182.653,196.239,156.471,196.445,200.797,177.926,177.302,...,227.168,219.875,227.324,227.598,222.308,227.230,218.956,206.125,190.970,171.040
27,8/8/2017,159.851,161.772,176.987,200.742,160.985,200.992,216.680,182.006,181.863,...,232.698,236.456,236.863,238.139,228.032,233.227,224.495,212.286,199.920,176.615
28,8/9/2017,164.978,166.859,182.167,211.035,171.206,206.130,229.609,195.021,195.202,...,248.373,244.604,251.946,251.210,235.304,237.760,233.631,221.423,207.645,184.796
29,8/10/2017,174.875,185.926,188.365,223.274,178.151,213.225,230.865,203.345,201.908,...,255.959,263.460,255.975,264.466,247.272,252.578,243.660,229.975,216.454,195.073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,9/21/2017,191.077,190.214,198.790,227.949,181.751,219.340,225.368,180.134,184.728,...,260.673,263.852,258.463,275.485,254.295,259.686,250.625,233.180,220.459,199.334
60,9/22/2017,192.119,191.243,199.847,228.972,182.785,220.390,226.425,181.214,185.774,...,261.194,264.873,259.469,276.487,254.740,260.705,250.679,234.236,221.513,200.281
61,9/25/2017,188.996,188.231,196.551,224.724,178.386,217.006,220.873,174.971,179.567,...,248.489,260.941,250.739,266.614,251.017,256.189,247.496,229.926,216.893,196.613
62,9/26/2017,192.019,192.682,196.944,227.391,179.189,217.156,224.750,177.740,183.950,...,245.053,255.558,246.909,259.949,252.440,258.132,248.565,231.870,219.056,198.240
63,9/27/2017,191.961,192.684,197.736,226.330,179.079,218.182,223.041,177.473,182.102,...,244.576,252.075,246.419,257.445,251.367,256.469,247.894,231.736,218.486,198.640
64,9/28/2017,193.862,194.423,198.871,229.188,180.931,219.140,226.747,181.310,185.840,...,246.212,253.710,248.982,258.975,252.868,258.257,249.198,234.087,220.992,200.533
65,9/29/2017,193.905,194.452,198.927,229.232,180.959,219.211,226.817,181.394,185.894,...,246.231,256.734,248.990,260.487,253.252,258.470,249.700,234.144,221.049,200.584
66,10/2/2017,191.741,191.987,196.617,227.158,178.990,216.783,224.368,178.737,183.653,...,243.672,255.433,248.357,257.166,250.770,255.925,247.261,231.181,218.820,197.450
67,10/3/2017,190.808,191.032,195.687,223.734,177.585,215.868,201.071,177.831,182.717,...,239.974,254.460,247.368,256.680,248.587,254.011,244.893,230.257,216.337,196.222
68,10/4/2017,190.358,190.566,195.247,223.278,177.120,215.437,198.643,169.597,169.402,...,239.496,253.981,246.877,256.185,248.140,253.564,244.447,228.790,214.803,194.179
69,10/5/2017,189.098,189.234,194.044,221.984,175.788,214.265,196.929,168.542,168.194,...,238.110,248.731,245.426,248.994,246.129,251.579,242.418,227.518,213.447,193.090
70,10/6/2017,187.965,187.990,194.495,222.295,173.992,214.831,197.000,168.999,168.497,...,237.248,247.750,240.498,249.000,246.315,251.587,242.726,227.452,213.125,192.893
71,10/9/2017,187.238,187.480,193.612,221.647,173.478,213.812,195.861,167.697,167.633,...,236.901,247.412,240.334,248.892,245.549,250.826,241.957,226.541,212.228,192.056
72,10/10/2017,187.858,189.573,193.749,219.699,173.563,212.942,196.042,167.392,166.761,...,232.447,243.460,237.856,245.398,244.914,250.276,241.264,223.929,210.319,190.767
73,10/11/2017,188.963,185.109,192.865,220.782,174.640,213.063,197.213,168.585,174.418,...,238.017,244.514,241.892,250.681,246.465,252.180,242.575,225.445,211.768,191.606
74,10/12/2017,188.963,185.109,192.865,220.782,174.640,213.063,197.213,168.585,172.593,...,240.090,244.514,241.892,250.681,246.437,252.110,242.575,225.369,211.646,191.606
75,10/13/2017,189.691,184.912,191.397,221.457,175.303,211.641,198.920,169.530,173.383,...,240.226,245.129,243.989,251.243,247.094,252.645,243.315,224.170,211.837,191.042
76,10/16/2017,189.232,184.434,193.043,221.075,174.974,213.592,197.869,168.694,172.655,...,239.915,244.906,243.848,250.901,246.601,252.139,242.830,225.213,212.674,191.600
77,10/17/2017,177.863,184.015,192.681,220.679,174.553,213.256,197.536,168.384,172.279,...,240.718,243.707,243.621,250.415,244.552,251.754,239.649,224.855,212.312,190.649
78,10/18/2017,177.477,183.596,192.320,220.284,174.133,212.920,197.203,168.074,171.903,...,240.268,243.259,242.391,249.929,244.170,251.369,239.269,224.625,211.951,190.373
79,10/19/2017,177.845,171.635,192.762,220.613,174.383,213.435,197.762,168.722,172.322,...,240.431,243.429,242.467,249.979,244.548,251.740,239.652,225.080,212.397,190.138
80,10/20/2017,176.393,170.170,191.343,219.172,172.920,212.035,196.338,167.312,170.879,...,238.951,241.950,238.718,248.483,243.103,250.291,238.210,223.657,210.973,188.704
81,10/23/2017,176.415,170.237,188.663,218.041,172.960,208.764,193.808,164.942,168.273,...,239.199,242.449,239.178,248.901,242.251,249.154,237.551,221.205,208.476,187.093
82,10/24/2017,177.032,170.824,189.296,218.637,173.539,209.411,194.485,165.643,168.909,...,239.753,243.005,240.459,249.420,241.778,249.774,236.335,221.844,209.112,187.721
83,10/25/2017,177.032,170.824,189.296,218.637,173.539,209.411,194.485,166.653,170.178,...,239.753,244.282,239.720,249.420,239.182,249.774,231.970,221.740,209.043,187.533
84,10/26/2017,177.393,171.170,189.846,220.155,173.916,210.103,197.335,168.307,171.876,...,239.951,244.438,239.795,249.484,240.118,250.644,232.952,222.430,209.942,188.052
85,10/27/2017,177.505,171.253,189.977,220.253,173.993,210.255,197.504,168.501,172.003,...,240.002,244.502,240.998,249.500,240.519,251.402,233.109,222.882,210.438,188.290
86,10/30/2017,172.446,168.846,194.368,219.777,174.629,213.587,195.170,167.041,168.367,...,236.751,245.254,236.374,244.911,235.760,248.915,226.804,222.617,209.485,188.278
87,10/31/2017,172.504,168.889,194.432,219.818,174.668,213.654,195.257,167.138,168.432,...,236.777,245.281,236.152,244.920,234.271,245.151,226.864,222.684,209.550,188.340
88,11/1/2017,172.558,168.929,194.493,217.426,170.759,213.717,193.003,167.232,168.493,...,239.460,243.982,239.576,249.327,234.171,244.822,226.919,222.549,209.077,188.271

In [10]:
# Get all dates and cusips
dates = dm['Date']
cusips = dm.columns[1:56]

In [11]:
dx = pd.DataFrame(columns=['Date', 'CUSIP', 'DM', 'PRICE'])
l = 0
for i in range(len(dates)):
    for j in range(len(cusips)):
        dm_val = dm[dm['Date']==dates[i]][cusips[j]].values[0]
        price_val = price[price['Date']==dates[i]][cusips[j]].values[0]
        cusip = str(cusips[j])
        dx.loc[l] = [dates[i], cusip, dm_val, price_val]
        l += 1

In [12]:
dx.head()

        Date      CUSIP       DM    PRICE
0  6/30/2017  3137G0AM1      161  116.655
1  6/30/2017  3137G0AY5   160.75  111.125
2  6/30/2017  3137G0BK4      177   109.08
3  6/30/2017  3137G0BW8  204.997  110.097
4  6/30/2017  3137G0CH0  213.638  109.915

In [21]:
dx['Date'] = dx['Date'].astype('datetime64[ns]')

dx.to_csv('/Users/armanarkilic/Desktop/historical.csv', index=False, date_format='%Y-%m-%d')

        Date      CUSIP       DM    PRICE
0  6/30/2017  3137G0AM1      161  116.655
1  6/30/2017  3137G0AY5   160.75  111.125
2  6/30/2017  3137G0BK4      177   109.08
3  6/30/2017  3137G0BW8  204.997  110.097
4  6/30/2017  3137G0CH0  213.638  109.915

In [ ]:
d = dx['Date']

In [22]:
raw_data = dx

In [25]:
raw_data.to_csv('/Users/armanarkilic/Desktop/historical.csv', index=False, date_format='%Y-%m-%d')